[build-system]
# Require setuptools and torch to be present before the build starts
requires = ["setuptools>=42", "wheel", "torch"]
build-backend = "setuptools.build_meta"

[project]
name = "diff_gaussian_rasterization"
version = "0.1.0" # You can adjust your version number
description = "Differentiable Gaussian Rasterization"
authors = [
    { name = "GRAPHDECO research group", email = "george.drettakis@inria.fr" }
]
license = { file = "LICENSE.md" }
dependencies = [
    "torch"
]

[tool.setuptools.packages.find]
include = ["diff_gaussian_rasterization"]
